config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  post 'items/add_to_cart/:id', to: 'items#add_to_cart', as: 'add_to_cart'
  delete 'items/remove_from_cart/:id', to: 'items#remove_from_cart', as: 'remove_from_cart'

  resources :items, only: %i[index show] do
    collection do
      get 'search_results'
      get 'filter_results'
      get 'cart'
    end
  end
  resources :about
  resources :contact
  resources :categories, only: %i[index show]
  root to: 'pages#home'
end

app/models/about.rb
# frozen_string_literal: true

class About < ApplicationRecord
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :category_name, presence: true
  validates :category_name, uniqueness: true
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :category
  has_many :order_item
  has_many :orders, through: :order_item

  validates :name, :cost, :image, presence: true
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  has_many :order_item
  has_many :items, through: :order_item

  validates :status, :cost, presence: true
end

app/models/order_item.rb
# frozen_string_literal: true

class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :order

  validates :quantity, :cost, presence: true
end

app/models/province.rb
# frozen_string_literal: true

class Province < ApplicationRecord
  has_many :users, dependent: :destroy

  validates :name, presence: true

  validates :name, uniqueness: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders, dependent: :destroy
  belongs_to :province

  validates :full_name, :password, :city, :address, presence: true

  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :intitialize_session
  before_action :load_cart

  def index
    @items = Item.all.page(params[:page]).per(12)
  end

  def show
    @items = Item.find(params[:id])
  end

  def cart; end

  def search_results
    @q = params[:search]
    @c = params[:category_name]

    @items = if @c.empty?
               Item.where('name LIKE ?', "%#{@q}%").page(params[:page]).per(12)
             else
               Item.where('name LIKE ? AND category_id = ?', "%#{@q}%", @c)
                   .page(params[:page])
             end
  end

  def filter_results
    @s = params[:onSale]
    @c = params[:cost]

    if @c == 'High'
      high_results
    elsif @c == 'Low'
      low_results
    end
  end

  def high_results
    @s = params[:onSale]

    @items = if @s == 'Sale'
               Item.where('onSale = 1').order(cost: :desc).page(params[:page])
                   .per(12)
             else
               Item.where('onSale = 0').order(cost: :desc).page(params[:page])
                   .per(12)
             end
  end

  def low_results
    @s = params[:onSale]

    @items = if @s == 'Sale'
               Item.where('onSale = 1').order(:cost).page(params[:page]).per(12)
             else
               Item.where('onSale = 0').order(:cost).page(params[:page]).per(12)
             end
  end

  def add_to_cart
    id = params[:id].to_i
    session[:cart] << id unless session[:cart].include?(id)
    flash[:notice] = 'Item successfully added to cart'
    redirect_to request.referrer
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete(id)
    redirect_to request.referrer
  end

  private

  def intitialize_session
    session[:item_quantity] ||= 0
    session[:cart] ||= []
  end

  def load_cart
    @cart = Item.find(session[:cart])
  end
end

app/helpers/about_helper.rb
# frozen_string_literal: true

module AboutHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/categorys_helper.rb
# frozen_string_literal: true

module CategorysHelper
end

app/helpers/contact_helper.rb
# frozen_string_literal: true

module ContactHelper
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/helpers/order_helper.rb
# frozen_string_literal: true

module OrderHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/provinces_helper.rb
# frozen_string_literal: true

module ProvincesHelper
end

app/helpers/searches_helper.rb
# frozen_string_literal: true

module SearchesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/items/_item.html.slim
.column.is-2
  .card
    .card-image
      figure.image.is-4by3
        = image_tag item.image, alt: item.name
    .card-content
      .media
        .media-content
          p.title.is-4
            = link_to item.name, item
          p.subtitle.is-6
            = number_to_currency item.cost
      .content

app/views/items/cart.html.slim
nav.breadcrumb.is-small aria-label="breadcrumbs"
  ul
    li
      = link_to 'Home', root_path
    li
      = link_to 'Store', items_path
    li.is-active
      |   
      p Cart
  br/
  - if flash[:notice]
    .notice= flash[:notice]
- if @cart.empty?
  .container
    div
      h1.title Shopping Cart
      p
        | Your shopping cart is currently empty. Please check out our #{link_to 'store to add items', items_path}
- else
  h1.title Shopping Cart
  .columns.is-multiline
    - @cart.each do |item|
      .column.is-2
        .card
          .card-image
            figure.image.is-4by3
              = image_tag item.image, alt: item.name
          .card-content
            .media
              .media-content
                p.title.is-4
                  = link_to item.name, item
                p.subtitle.is-6
                  = number_to_currency item.cost
                p.subtitle.is-6
                  = @item_quantity
            = form_tag(cart_items_path, :method => "get") do
              p
                = link_to "Remove from Cart", remove_from_cart_path(item), method: :delete, class:"button is-info"

app/views/items/filter_results.html.slim
nav.breadcrumb.is-small aria-label="breadcrumbs"
  ul
    li
      = link_to 'Home', root_path
    li
      = link_to 'Store', items_path
    li.is-active
      |   
      | Filter Results
.columns.is-multiline
  = render partial: @items
.column.is-12
  = paginate @items

app/views/items/index.html.slim
nav.breadcrumb.is-small aria-label="breadcrumbs"
  ul
    li
      = link_to 'Home', root_path
    li.is-active
      a href="#"  Store
.columns.is-multiline
  = render partial: @items
.column.is-12
  = paginate @items

app/views/items/search_results.html.slim
nav.breadcrumb.is-small aria-label="breadcrumbs"
  ul
    li
      = link_to 'Home', root_path
    li
      = link_to 'Store', items_path
    li.is-active
      |   
      | Search Results
.columns.is-multiline
  = render partial: @items
.column.is-12
  = paginate @items

app/views/items/show.html.slim
nav.breadcrumb.is-small aria-label="breadcrumbs"
  ul
    li
      = link_to 'Home', root_path
    li
      = link_to 'Store', items_path
    li.is-active
      |   
      | #{@items.name}
  br/
  - if flash[:notice]
    .notice= flash[:notice]
.column.is-2
  .card
    .card-image
      figure.image.is-4by3
        = image_tag @items.image, alt: @items.name
    .card-content
      .media
        .media-content
          p.title.is-4
            = @items.name
          p.subtitle.is-6
            = number_to_currency @items.cost
      .content
        = @items.lore
      p
        | Quantity: #{@items.quantity}
      br/
      = form_tag(cart_items_path, :method => "get", id: "add-to-cart-form") do
        p= link_to "Add to Cart", add_to_cart_path(@items.id), method: :post, class:"button is-info"