config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  post 'items/add_to_cart/:id', to: 'items#add_to_cart', as: 'add_to_cart'
  delete 'items/remove_from_cart/:id', to: 'items#remove_from_cart', as: 'remove_from_cart'

  resources :items, only: %i[index show] do
    collection do
      get 'search_results'
      get 'filter_results'
      get 'cart'
    end
  end
  resources :about
  resources :contact
  resources :categories, only: %i[index show]
  root to: 'pages#home'
end

app/models/about.rb
# frozen_string_literal: true

class About < ApplicationRecord
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :category_name, presence: true
  validates :category_name, uniqueness: true
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :category
  has_many :order_item
  has_many :orders, through: :order_item

  validates :name, :cost, :image, presence: true
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  has_many :order_item
  has_many :items, through: :order_item

  validates :status, :cost, presence: true
end

app/models/order_item.rb
# frozen_string_literal: true

class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :order

  validates :quantity, :cost, presence: true
end

app/models/province.rb
# frozen_string_literal: true

class Province < ApplicationRecord
  has_many :users, dependent: :destroy

  validates :name, presence: true

  validates :name, uniqueness: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders, dependent: :destroy
  belongs_to :province

  validates :full_name, :password, :city, :address, presence: true

  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/helpers/about_helper.rb
# frozen_string_literal: true

module AboutHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/categorys_helper.rb
# frozen_string_literal: true

module CategorysHelper
end

app/helpers/contact_helper.rb
# frozen_string_literal: true

module ContactHelper
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/helpers/order_helper.rb
# frozen_string_literal: true

module OrderHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/provinces_helper.rb
# frozen_string_literal: true

module ProvincesHelper
end

app/helpers/searches_helper.rb
# frozen_string_literal: true

module SearchesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Dota</title>
    <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

            <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
                <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
                    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
</head>

<body>
    <nav class="navbar is-black" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item">
                <img src="https://i.imgur.com/9E153BZ.png" alt="#" width="60" height="30">
            </a>

            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                <%=link_to 'Home', root_path, class: 'navbar-item' %>
                    <%=link_to 'Store', items_path, class: 'navbar-item' %>
                        <%=link_to 'Categories', categories_path, class: 'navbar-item' %>
                        <%=link_to 'Contact Us', '/contact', class:'navbar-item' %>
                                <%=link_to 'About', '/about', class:'navbar-item'%>

            </div>

            <div class="navbar-end">
                <div class="navbar-item">
                    <div>
                        <%= form_tag(filter_results_items_path, :method => "get", id: "filter-form", class: 'navbar-item') do %>
                            <%= select_tag :onSale, options_for_select(["Sale", "Regular Price" ]), class: 'navbar-item' %>
                                <%= select_tag :cost, options_for_select(["High", "Low" ]), class: 'navbar-item' %>
                                    <%= submit_tag "Filter", class:"button is-info" %>
                                        <% end %>
                    </div>
                </div>

                <div class="navbar-item">
                    <div>
                        <%= form_tag(search_results_items_path, :method => "get", id: "search-form", class: 'navbar-item') do %>
                            <%= select_tag :category_name, options_from_collection_for_select(Category.all, 'id', 'category_name'), :prompt => "Category", class: 'navbar-item' %>
                                <%= text_field_tag :search, params[:search], placeholder: "Search a Product", class: "input", class: 'navbar-item'%>
                                    <%= submit_tag "Search", class:"button is-info" %>
                                        <% end %>
                    </div>
                </div>

                <div class="navbar-item">
                    <div class="buttons">
                        <%= link_to "Cart", cart_items_path, method: :get, class:"button is-info" %>
                            <%= link_to "Checkout", '#', method: :get, class:"button is-info" %>
                    </div>
                </div>

            </div>
        </div>
    </nav>
    <section class="section">
        <nav class="navbar is-white" role="navigation" aria-label="main navigation">
            <div class="navbar-end">
                <div class="navbar-item">
                    <% if user_signed_in? %>
                        <div>
                            Logged in as&nbsp; <strong><%= current_user.full_name %></strong>
                        </div>
                </div>
                <div class="navbar-item">
                        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-item'  %>
                            <% else %>
                                <%= link_to "Sign up", new_user_registration_path, class: 'navbar-item'  %>
                                    <%= link_to "Login", new_user_session_path, class:'navbar-item'  %>
                                        <% end %>
                </div>
            </div>
        </nav>
        <%= yield %>
    </section>
</body>

</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Dota
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    link href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css" rel="stylesheet" /
  body
    nav.navbar.is-black aria-label=("main navigation") role="navigation"
      .navbar-brand
        a.navbar-item
          img alt="#" height="30" src="https://i.imgur.com/9E153BZ.png" width="60" /
        a.navbar-burger.burger aria-expanded="false" aria-label="menu" data-target="navbarBasicExample" role="button"
          span aria-hidden="true"
          span aria-hidden="true"
          span aria-hidden="true"
      #navbarBasicExample.navbar-menu
        .navbar-start
          = link_to 'Home', root_path, class: 'navbar-item'
          = link_to 'Store', items_path, class: 'navbar-item'
          = link_to 'Categories', categories_path, class: 'navbar-item'
          = link_to 'Contact Us', '/contact', class:'navbar-item'
          = link_to 'About', '/about', class:'navbar-item'
        .navbar-end
          .navbar-item
            div
              = form_tag(filter_results_items_path, :method => "get", id: "filter-form", class: 'navbar-item') do
                = select_tag :onSale, options_for_select(["Sale", "Regular Price" ]), class: 'navbar-item'
                = select_tag :cost, options_for_select(["High", "Low" ]), class: 'navbar-item'
                = submit_tag "Filter", class:"button is-info"
          .navbar-item
            div
              = form_tag(search_results_items_path, :method => "get", id: "search-form", class: 'navbar-item') do
                = select_tag :category_name, options_from_collection_for_select(Category.all, 'id', 'category_name'), :prompt => "Category", class: 'navbar-item'
                = text_field_tag :search, params[:search], placeholder: "Search a Product", class: "input", class: 'navbar-item'
                = submit_tag "Search", class:"button is-info"
          .navbar-item
            .buttons
              = link_to "Cart", cart_items_path, method: :get, class:"button is-info"
              = link_to "Checkout", '#', method: :get, class:"button is-info"
    section.section
      nav.navbar.is-white aria-label=("main navigation") role="navigation"
        .navbar-end
          .navbar-item
            - if user_signed_in?
              div
                | Logged in as 
                strong= current_user.full_name
          .navbar-item
            = link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-item'
            - else
              = link_to "Sign up", new_user_registration_path, class: 'navbar-item'
              = link_to "Login", new_user_session_path, class:'navbar-item'
      = yield

app/views/pages/home.html.slim
.section
  .container
    .columns.is-centered
      .column.is-6
        .container
          div
            h1.title Welcome to the Dota Store!
            p We here at the Dota Store bring all the in game items to real life for you to purchase.
            p
              | Please take a moment to check out our online store by clicking
              | #{link_to ' here', items_path}